### ISSUE TITLE
faye.js not found on my production url.

### ISSUE THREAD

**Issue by leena-bhise** [ryanb/private_pub#115]
I have implemented private pub in my rails app. it is working fine on my local. but on my production server it is not working. it doesn't find faye.js there. 

production url : http://52.11.111.224

private_pub.yml entry for production : 
production:
  server: "http://52.11.111.224:9292/faye/faye"
  secret_token: "awesomejobmanager"

Do you have any suggestion for this.

**Comment by gabrieltong** [comment]
+1

**Comment by gabrieltong** [comment]
after I change my private_pub.yml to
```
production:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
  signature_expiration: 3600 # one hour
```
I think it's only a config error , and I don't know how .
