### ISSUE TITLE
certificate verify failed

### ISSUE THREAD

**Issue by tomoyuki28jp** [ryanb/private_pub#68]
curl -O 'https://mydomain.com:4443/faye.js'
This command works over http, but not on the server where my private_pub is running. Any idea why?

I get this error.
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

**Comment by rbcs** [comment]
Hi, I am facing the same issue. What i did till now is i added content of .ca file into .crt file but still getting same error '<SSL_incomp>'. Please help me if anyone know about this.
Thanks

**Comment by ovinix** [comment]
@rbcs I had <SSL_incomp> issue using Thin and "certificate verify failed" in my Rails app log. The problem was inside "private_pub" publish_to function.
This error happend to me then "http" request was created using Net::HTTP.new with use_ssl set to 'true'. I forked "private_pub" and changed publish_message function a bit:
```
if http.use_ssl? and config[:cert_path].present? and config[:key_path].present?
        cert = File.read(config[:cert_path])
        key = File.read(config[:key_path])
        http.cert = OpenSSL::X509::Certificate.new(cert)
        http.key = OpenSSL::PKey::RSA.new(key)
        http.verify_mode = OpenSSL::SSL::VERIFY_NONE
 end
```
But I don't know if setting http.verify_mode to OpenSSL::SSL::VERIFY_NONE is good idea.

So now you can set your 'private_pub.yml' like this:
```
production:
  server: "https://localhost:4443/faye"
  secret_token: "secret"
  signature_expiration: 3600 # one hour
  cert_path: "/path_to_ssl/server.crt"
  key_path: "/path_to_ssl/server.key"
```

[You can see my fork here.](https://github.com/ovinix/private_pub)

Set your Gemfile like this:
```
gem 'private_pub', :git => 'git://github.com/ovinix/private_pub.git'

```
