### ISSUE TITLE
/faye.js is not available over ssl 

### ISSUE THREAD

**Issue by tamvm** [ryanb/private_pub#96]
I managed to enable SSL on my server with ryanb's guide at https://github.com/ryanb/private_pub#serving-faye-over-https-with-thin. But I can't connect to 4443 port to load faye.js. Here is some of my config:

config/private_pub.yml

```
production:
  server: "https://<my-website>:4443/faye"
  secret_token: "<%= ActiveSupport::SecureRandom.hex(32) %>"
  signature_expiration: 86400 # one day
```

config/private_pub_thin.yml

```

---
port: 4443
ssl: true
ssl_key_file: <ssl_key>.key
ssl_cert_file: <ssl_cert>.crt
environment: production
rackup: private_pub.ru
daemonize: true
```

Then start with following command:

```
bundle exec thin -C config/private_pub_thin.yml start
```

I dont understand why I can't connect to https://<my-website>:4443/faye.js Is there anyone successfully setup private_pub over ssl? 

Thanks a lot
